//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoLeadX.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AutoLeadX.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1234 {
            get {
                object obj = ResourceManager.GetObject("_1234", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _200px_Green_cross_svg {
            get {
                object obj = ResourceManager.GetObject("200px-Green_cross.svg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap arrow_refresh {
            get {
                object obj = ResourceManager.GetObject("arrow_refresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap back1 {
            get {
                object obj = ResourceManager.GetObject("back1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap back2 {
            get {
                object obj = ResourceManager.GetObject("back2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aquafon||Abkhazia||GE-AB||67||289
        ///A-Mobile||Abkhazia||GE-AB||88||289
        ///AWCC||Afghanistan||AF||1||412
        ///Roshan||Afghanistan||AF||20||412
        ///MTN||Afghanistan||AF||40||412
        ///Etisalat||Afghanistan||AF||50||412
        ///WASEL||Afghanistan||AF||55||412
        ///Salaam||Afghanistan||AF||80||412
        ///Salaam||Afghanistan||AF||88||412
        ///Telekom||Albania||AL||1||276
        ///Vodafone||Albania||AL||2||276
        ///Eagle Mobile||Albania||AL||3||276
        ///Plus Communication||Albania||AL||4||276
        ///Mobilis||Algeria||DZ||1||603
        ///Djezzy||Algeria||DZ||2||603
        ///Ooredoo||Alg [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string carrierlist {
            get {
                return ResourceManager.GetString("carrierlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AD|42.546245|1.601554|Andorra
        ///AE|23.424076|53.847818|United Arab Emirates
        ///AF|33.93911|67.709953|Afghanistan
        ///AG|17.060816|-61.796428|Antigua and Barbuda
        ///AI|18.220554|-63.068615|Anguilla
        ///AL|41.153332|20.168331|Albania
        ///AM|40.069099|45.038189|Armenia
        ///AN|12.226079|-69.060087|Netherlands Antilles
        ///AO|-11.202692|17.873887|Angola
        ///AQ|-75.250973|-0.071389|Antarctica
        ///AR|-38.416097|-63.616672|Argentina
        ///AS|-14.270972|-170.132217|American Samoa
        ///AT|47.516231|14.550072|Austria
        ///AU|-25.274398|133.775136|Australia [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string coordinate {
            get {
                return ResourceManager.GetString("coordinate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AD
        ///AE|ar
        ///AF
        ///AG|en
        ///AI
        ///AL|ar
        ///AM
        ///AO
        ///AR|es
        ///AS
        ///AT|de
        ///AU|en-AU
        ///AW
        ///AX
        ///AZ
        ///BA
        ///BB
        ///BD
        ///BE
        ///BF
        ///BG
        ///BH|ar
        ///BI
        ///BJ
        ///BL
        ///BM
        ///BN
        ///BO|es
        ///BQ
        ///BR|pt-BR
        ///BS
        ///BT
        ///BW
        ///BY
        ///BZ
        ///CA|en
        ///CC
        ///CD|ar
        ///CF
        ///CG
        ///CH|de
        ///CI
        ///CK
        ///CL|es
        ///CM
        ///CN|zh-Hant
        ///CO|es
        ///CR|es
        ///CU
        ///CV
        ///CW
        ///CX
        ///CY
        ///CZ|cs
        ///DE|de
        ///DJ
        ///DK|da
        ///DM
        ///DO|es
        ///DZ|ar
        ///EC|es
        ///EE
        ///EG|ar
        ///ER
        ///ES|es
        ///ET
        ///FI|fi
        ///FJ
        ///FK
        ///FM
        ///FO
        ///FR|fr
        ///GA
        ///GB|en-GB
        ///GD
        ///GE
        ///GF
        ///GG
        ///GH
        ///GI
        ///GL
        ///GM
        ///GN
        ///GP
        ///GQ
        ///GR|el
        ///GT|es
        ///GU
        ///GW
        ///GY
        ///HK|zh-HK
        ///HN|es
        ///HR|hr
        ///HT
        ///HU|hu
        ///ID|id
        ///IE
        ///IL|he [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string countrycodeiOS {
            get {
                return ResourceManager.GetString("countrycodeiOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DeleteRed {
            get {
                object obj = ResourceManager.GetObject("DeleteRed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPod5,1 320 568 2
        ///iPod7,1 320 568 2
        ///iPhone4,1 320 480 2
        ///iPhone5,1 320 568 2
        ///iPhone5,2 320 568 2
        ///iPhone5,3 320 568 2
        ///iPhone5,4 320 568 2
        ///iPhone6,1 320 568 2
        ///iPhone6,2 320 568 2
        ///iPhone7,1 414 736 3
        ///iPhone7,2 375 667 2
        ///iPhone8,1 375 667 2
        ///iPhone8,2 414 736 3
        ///iPhone8,4 320 568 2
        ///iPhone9,1 375 667 2
        ///iPhone9,2 414 736 3
        ///iPhone9,3 375 667 2
        ///iPhone9,4 414 736 3
        ///iPhone10,1 375 667 2
        ///iPhone10,4 375 667 2
        ///iPhone10,2 414 736 3
        ///iPhone10,5 414 736 3
        ///iPad4,1 768 1024 2 
        ///iPad4,2 768 1024 2
        ///iPad4,4 7 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string deviceScreen {
            get {
                return ResourceManager.GetString("deviceScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hotmail.com
        ///gmail.com
        ///yahoo.com
        ///rocketmail.com
        ///msn.com
        ///live.com
        ///mail.com.
        /// </summary>
        internal static string emaildomain {
            get {
                return ResourceManager.GetString("emaildomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap enter {
            get {
                object obj = ResourceManager.GetObject("enter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fast_delivery_3 {
            get {
                object obj = ResourceManager.GetObject("fast_delivery_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Fast_forward_icon {
            get {
                object obj = ResourceManager.GetObject("Fast_forward_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aaron
        ///Aaron
        ///Abbey
        ///Abbie
        ///Abby
        ///Abdul
        ///Abe
        ///Abel
        ///Abigail
        ///Abraham
        ///Abram
        ///Ada
        ///Adah
        ///Adalberto
        ///Adaline
        ///Adam
        ///Adam
        ///Adan
        ///Addie
        ///Adela
        ///Adelaida
        ///Adelaide
        ///Adele
        ///Adelia
        ///Adelina
        ///Adeline
        ///Adell
        ///Adella
        ///Adelle
        ///Adena
        ///Adina
        ///Adolfo
        ///Adolph
        ///Adria
        ///Adrian
        ///Adrian
        ///Adriana
        ///Adriane
        ///Adrianna
        ///Adrianne
        ///Adrien
        ///Adriene
        ///Adrienne
        ///Afton
        ///Agatha
        ///Agnes
        ///Agnus
        ///Agripina
        ///Agueda
        ///Agustin
        ///Agustina
        ///Ahmad
        ///Ahmed
        ///Ai
        ///Aida
        ///Aide
        ///Aiko
        ///Aileen
        ///Ailene
        ///Aimee
        ///Aisha
        ///Aja
        ///Akiko
        ///Akilah
        ///Al
        ///Alaina
        ///Alaine
        ///Alan
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string firstname {
            get {
                return ResourceManager.GetString("firstname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPod5,1
        ///iPod7,1
        ///iPhone4,1
        ///iPhone5,1
        ///iPhone5,2
        ///iPhone5,3
        ///iPhone5,4
        ///iPhone6,1
        ///iPhone6,2
        ///iPhone7,1
        ///iPhone7,2
        ///iPhone8,1
        ///iPhone8,2
        ///iPhone4,1
        ///iPhone5,1
        ///iPhone5,2
        ///iPhone5,3
        ///iPhone5,4
        ///iPhone6,1
        ///iPhone6,2
        ///iPhone7,1
        ///iPhone7,2
        ///iPhone8,1
        ///iPhone8,2
        ///iPhone4,1
        ///iPhone5,1
        ///iPhone5,2
        ///iPhone5,3
        ///iPhone5,4
        ///iPhone6,1
        ///iPhone6,2
        ///iPhone7,1
        ///iPhone7,2
        ///iPhone8,1
        ///iPhone8,2
        ///iPad2,5
        ///iPad2,6
        ///iPad2,7
        ///iPad3,1
        ///iPad3,2
        ///iPad3,3
        ///iPad3,4
        ///iPad3,5
        ///iPad3,6
        ///iPad4,1
        ///iPad4,2
        ///iPad4,4
        ///iPad4,5
        ///iPad4,6
        ///iPad4 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string iDevice {
            get {
                return ResourceManager.GetString("iDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English|en
        ///English (British)|en-GB
        ///English (Australian)|en-AU
        ///English (Canadian)|en-CA
        ///English (Indian)|en-IN
        ///French|fr
        ///French (Canadian)|fr-CA
        ///Spanish|es
        ///Spanish (Mexico)|es-MX
        ///Portuguese|pt
        ///Portuguese (Brazil)|pt-BR
        ///Italian|it
        ///German|de
        ///Chinese (Simplified)|zh-Hans
        ///Chinese (Traditional)|zh-Hant
        ///Chinese (Hong Kong)|zh-HK
        ///Dutch|nl
        ///Japanese|ja
        ///Korean|ko
        ///Vietnamese|vi
        ///Russian|ru
        ///Swedish|sv
        ///Danish|da
        ///Finnish|fi
        ///Norwegian (Bokmal)|nb
        ///Turkish|tr
        ///Greek|el
        ///Indonesian|id
        ///Malay|ms
        ///Thai|t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string languagecode {
            get {
                return ResourceManager.GetString("languagecode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lastname
        ///Aaberg
        ///Aaby
        ///Aadland
        ///Aagaard
        ///Aakre
        ///Aaland
        ///Aalbers
        ///Aalderink
        ///Aalund
        ///Aamodt
        ///Aamot
        ///Aanderud
        ///Aanenson
        ///Aanerud
        ///Aarant
        ///Aardema
        ///Aarestad
        ///Aarhus
        ///Aaron
        ///Aarons
        ///Aaronson
        ///Aarsvold
        ///Aas
        ///Aasby
        ///Aase
        ///Aasen
        ///Aavang
        ///Abad
        ///Abadi
        ///Abadie
        ///Abair
        ///Abaja
        ///Abajian
        ///Abalos
        ///Abaloz
        ///Abar
        ///Abarca
        ///Abare
        ///Abascal
        ///Abasta
        ///Abate
        ///Abati
        ///Abatiell
        ///Abato
        ///Abatti
        ///Abaunza
        ///Abaya
        ///Abbadessa
        ///Abbamonte
        ///Abbas
        ///Abbasi
        ///Abbassi
        ///Abbate
        ///Abbatiello
        ///Abbay
        ///Abbe
        ///Abbed
        ///Abbenante
        ///Abbey
        ///Abbinanti
        ///Abbington
        ///A [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string lastname {
            get {
                return ResourceManager.GetString("lastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Pause_icon {
            get {
                object obj = ResourceManager.GetObject("Pause_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Pause_icon__1_ {
            get {
                object obj = ResourceManager.GetObject("Pause_icon__1_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Phone_icon {
            get {
                object obj = ResourceManager.GetObject("Phone_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Play_icon {
            get {
                object obj = ResourceManager.GetObject("Play_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Play_icon__1_ {
            get {
                object obj = ResourceManager.GetObject("Play_icon__1_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap red_stop_playback {
            get {
                object obj = ResourceManager.GetObject("red_stop_playback", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap respring {
            get {
                object obj = ResourceManager.GetObject("respring", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Resume_Button_48 {
            get {
                object obj = ResourceManager.GetObject("Resume_Button_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to touch(x,y)
        ///swipe(x,y,x1,y1,time)
        ///randomemail()
        ///randomemaildomain()
        ///randomtext(x,y)
        ///randomnumber(x,y)
        ///wait(x)
        ///send(&apos;text&apos;)
        ///randomfirstname()
        ///randomlastname()
        ///waitrandom(x,y)
        ///close(&apos;appname&apos;)
        ///open(&apos;appname&apos;).
        /// </summary>
        internal static string scriptcommand {
            get {
                return ResourceManager.GetString("scriptcommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Skype_icon {
            get {
                object obj = ResourceManager.GetObject("Skype_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap social_facebook_box_blue_icon {
            get {
                object obj = ResourceManager.GetObject("social_facebook_box_blue_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap start_green_16px_516575_easyicon_net {
            get {
                object obj = ResourceManager.GetObject("start_green_16px_516575_easyicon_net", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Stop_icon {
            get {
                object obj = ResourceManager.GetObject("Stop_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Stop_icon__1_ {
            get {
                object obj = ResourceManager.GetObject("Stop_icon__1_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Africa/Abidjan&quot;,&quot;Africa/Accra&quot;,&quot;Africa/Addis_Ababa&quot;,&quot;Africa/Algiers&quot;,&quot;Africa/Asmara&quot;,&quot;Africa/Bamako&quot;,&quot;Africa/Bangui&quot;,&quot;Africa/Banjul&quot;,&quot;Africa/Bissau&quot;,&quot;Africa/Blantyre&quot;,&quot;Africa/Brazzaville&quot;,&quot;Africa/Bujumbura&quot;,&quot;Africa/Cairo&quot;,&quot;Africa/Casablanca&quot;,&quot;Africa/Ceuta&quot;,&quot;Africa/Conakry&quot;,&quot;Africa/Dakar&quot;,&quot;Africa/Dar_es_Salaam&quot;,&quot;Africa/Djibouti&quot;,&quot;Africa/Douala&quot;,&quot;Africa/El_Aaiun&quot;,&quot;Africa/Freetown&quot;,&quot;Africa/Gaborone&quot;,&quot;Africa/Harare&quot;,&quot;Africa/Johannesburg&quot;,&quot;Africa/Juba&quot;,&quot;Africa/Kampala&quot;,&quot;Africa/Khartoum&quot;,&quot;Africa/Kigali&quot;,&quot;Africa/K [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string timezone {
            get {
                return ResourceManager.GetString("timezone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8.0|12A365
        ///8.0.1|12A402
        ///8.0.2|12A405
        ///8.1|12B411
        ///8.1.1|12B435
        ///8.1.2|12B440
        ///8.1.3|12B466
        ///8.2|12D508
        ///8.3|12F70
        ///8.4|12H143
        ///8.4.1|12H321
        ///9.0|13A344
        ///9.0.1|13A404
        ///9.0.2|13A452
        ///9.1|13B143.
        /// </summary>
        internal static string version {
            get {
                return ResourceManager.GetString("version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Yahoo_Messenger_icon {
            get {
                object obj = ResourceManager.GetObject("Yahoo_Messenger_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
